### chatGPT한테 요청
POST https://api.openai.com/v1/chat/completions
content-Type: application/json
Authorization: Bearer sk-proj-KBRoz4HFJOgiJKPKXII1T3BlbkFJu4XLp8I7PtMdZK546Eeb

{
  "model": "gpt-3.5-turbo",
  "messages": [{
    "role": "user",
    "content": "안녕"
  }],
  "stream": true
}

### 우리 서버로 요청
POST http://localhost:8080/chatbot
content-Type: application/json

{
"question": "데이터베이스 마이그레이션을 자동으로 하고싶어. 방법을 알려줘."
}
