# sam build
# sam deploy --stack-name fmarket-backend --s3-bucket lambda-package-$UID --capabilities CAPABILITY_IAM
# sam list endpoints --output json --stack-name fmarket-backend
AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Timeout: 600

Resources:
  CloudyBackendApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: 'prod'
  CloudyBackendFunction:
    Type: AWS::Serverless::Function
    Properties:
      #aws에서 계정 ID, role은 role.tf 참고
      Role: arn:aws:iam::767397922066:role/cloudy-lambda-role
      CodeUri: .
      Handler: com.s207.cloudy.LambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      #      SnapStart:
      #        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 512
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        CloudyBackendApi:
          Type: Api
          Properties:
            Path: /
            Method: ANY
            RestApiId:
              Ref: CloudyBackendApi
        CloudyBackendApiElse:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
            RestApiId:
              Ref: CloudyBackendApi
      VpcConfig:
        SecurityGroupIds:
        # 보안그룹 default 확인하기
          - sg-0c2237dd707dc6b09
        #private vpc id 2가지 이용
        SubnetIds:
          - subnet-0253ac03a3ec70057
          - subnet-08fc48b8da6f4f371
      SnapStart:
        ApplyOn: PublishedVersions