import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GoogleAnalytics from '@/components/common/GoogleAnalytics'
import '../styles/globals.scss'
import Header from '@/components/common/Header'
import Auth from '@/context/auth'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Auth>
          <GoogleAnalytics />
          <Header />
          <div style={{ paddingTop: 80 }}>{children}</div>
        </Auth>
      </body>
    </html>
  )
}
