import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import GoogleAnalytics from '@/components/common/GoogleAnalytics'
import '../styles/globals.scss'
import Auth from '@/context/auth'
import Navbar from '@/components/LoginButton'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Auth>{children}</Auth>
      </body>
      <GoogleAnalytics />
    </html>
  )
}
