spring:
  application:
    name: chatbot-server
  cloud:
    aws:
      credentials:
        access-key: AKIA3FLD3AUJDWR3ILYN
        secret-key: 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
      dynamodb:
        region: ap-northeast-2
        endpoint: https://dynamodb.ap-northeast-2.amazonaws.com
  devtools:
    restart:
      enabled: false



openai:
    key: ${OPENAI_KEY}
pinecone:
  key: ${PINECONE_KEY}
  env:
    qna: aped-4627-b74a
  #    qna: ${PINECONE_ENV_QNA}
  id:
    #    qna: ${PINECONE_ID_QNA}
    qna: kyr8e0r
server:
  servlet:
    encoding:
      charset: UTF-8

