spring:
  application:
    name: chatbot-server




openai:
    key: ${OPENAI_KEY}
pinecone:
  key: ${PINECONE_KEY}
  env:
    qna: aped-4627-b74a
  #    qna: ${PINECONE_ENV_QNA}
  id:
    #    qna: ${PINECONE_ID_QNA}
    qna: kyr8e0r
server:
  servlet:
    encoding:
      charset: UTF-8

amazon:
  aws:
    credentials:
      accesskey: ${AWS_ACCESS_KEY}
      secretkey: ${AWS_SECRET_KEY}
    dynamodb:
      endpoint: https://dynamodb.ap-northeast-2.amazonaws.com